# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - "wget https://s3.amazonaws.com/textblob/nltk_data.tar.gz"
  - "tar -xzvf nltk_data.tar.gz -C ~"

install:
  - pip install -U .
  - curl https://raw.github.com/sloria/TextBlob/master/download_corpora_lite.py | python

script: python run_tests.py
